version: "3.8"

# Define networks
networks:
  frontend:
    external: true #This network exists because we created it with the base install

# Create changedetection container
services:
  changedetection:
    container_name: changedetection
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    restart: always
    # ports:
      # - "5000:5000 # Not required if using the base install
    networks:
      - frontend