version: "3.8"

# Define networks
networks:
  frontend:
    external: true #This network exists because we created it with the base install

# Create libreddit container
services:
  libreddit:
    container_name: libreddit
    image: spikecodes/libreddit:latest
    restart: always
    ports:
      # - "8080:8080" # Not required if using the base install
    networks:
      - frontend