version: "3.8"

# Create a volume for portainer
volumes:
  portainer_data:

# Create frontend and backend networks
networks:
  frontend:
    name: frontend
  backend:
    name: backend

# Create Nginx Proxy Manager and Portainer containers
services:
  nginx_proxy_manager:
    container_name: nginx_proxy_manager
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    networks:
      - frontend
      - backend
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - backend