version: "3.8"

# Define networks
networks:
  frontend:
    external: true # This network exists because we created it with the base install

# Define volumes
volumes:
  uptime_kuma_data:
    name: uptime_kuma_data

# Create uptime kuma container
services:
  uptime_kuma:
    image: louislam/uptime-kuma:latest
    restart: always
    container_name: uptime_kuma
    networks:
      - frontend
    volumes:
      - uptime_kuma_data:/app/data
    # ports:
      # - 3001:3001 # Not required if using the base install