version: "3.8"

# Define networks
networks:
# This network gets created by my base-install compose file. Remove it if you aren't using that.
  frontend:
    external: true # This network exists because we created it with the base install

# Create volumes
volumes:
  forgejo_data:
    name: forgejo_data

# Create forgejo container
services:
  forgejo:
    container_name: forgejo
    image: codeberg.org/forgejo/forgejo:7
    restart: unless-stopped
    volumes:
      - forgejo_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - frontend
    # ports:
      # - "3000:3000" # Not required if using the base install
      # - "222:22" # Not required if using the base install
    environment:
      - TZ=America/Toronto