version: "3.8"

# Define networks
networks:
# These networks get created by my base-install compose file. Remove them if you aren't using that.
  frontend:
    external: true
  backend:
    external: true

# Create volumes
volumes:
  jellyfin_config:
    name: jellyfin_config

# Create Jellyfin container
services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    volumes:
      - jellyfin_config:/config
      - type: bind
        source: /media/media_drive/tv
        target: /tv
      - type: bind
        source: /media/media_drive/movies
        target: /movies
    networks:
      - frontend
      - backend
    # ports:
      # - 8096:8096 # Not required if using the base install
    environment:
      - TZ=America/Toronto