version: "3.8"

# Define networks
networks:
  frontend:
    external: true # This network exists because we created it with the base install
  # Uncomment the lines below if you are using my pihole container
  # pihole:
    # external: true # Created with the pihole container

# Define volumes
volumes:
  wg-easy:
    name: wg-easy

# Create wg-easy container
services:
  wg-easy:
    image: weejewel/wg-easy:latest
    container_name: wg-easy
    networks:
      - pihole
    volumes:
      - wg-easy:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    environment:
      - WG_HOST=wireguard.your.domain # Change this to your host's public address
      - PASSWORD=foobar123 # Change this to a secure password
      # Uncomment the line below if you are using my pihole container
      # - WG_DEFAULT_DNS=172.20.0.2
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always