version: "3.8"

# Define networks
networks:
  frontend:
    external: true # This network exists because we created it with the base install
  backend:
    external: true # This network exists because we created it with the base install

# Create pihole container
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - frontend
      - backend
    ports:
      - XXX.XXX.X.XXX:53/tcp # Replace the Xs with the IP of the machine or VM hosting this container
      - XXX.XXX.X.XXX:53:53/udp # Replace the Xs with the IP of the machine or VM hosting this container
      - 80:80/tcp
    environment:
      TZ: America/Toronto
      WEBPASSWORD: changeme # Replace this with a strong password
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: always