version: "3.8"

# Define networks
networks:
  frontend:
    external: true # This network exists because we created it with the base install
  backend:
    external: true # This network exists because we created it with the base install

# Define volumes
volumes:
  nextcloud_config:
    name: nextcloud_config
  nextcloud_data:
    name: nextcloud_data
  nextcloud_db:
    name: nextcloud_db

# Create nextcloud and nextcloud_db container
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    restart: always
    container_name: nextcloud
    networks:
      - frontend
      - backend
    volumes:
      - nextcloud_config:/config
      - nextcloud_data:/data
    # ports:
      # - 443:443 # Not required if using the base install
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=changeme
      - MYSQL_HOST=nextcloud_db
  nextcloud_db:
    image: lscr.io/linuxserver/mariadb:latest
    restart: always
    container_name: nextcloud_db
    networks:
      - backend
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pleasechangeme
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
