version: "3.8"

# Define networks
networks:
  frontend:
    external: true #This network exists because we created it with the base install

# Define volumes
volumes:
  calibre:
    name: calibre
  calibre-web:
    name: calibre-web

# Create calibre and calibre-web containers
services:
  calibre:
    container_name: calibre
    image: linuxserver/calibre:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - PASSWORD=changeme
    volumes:
      - calibre:/config
    restart: always
    # ports:
      # - "8080:8080" # Not required if using the base install
      # - "8081:8081" # Not required if using the base install
    networks:
      - frontend

  calibre-web:
    container_name: calibre-web
    image: linuxserver/calibre-web:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional - adds ability to convert files
    volumes:
      - calibre-web:/config
      - calibre:/books
    restart: always
    # ports:
      # - "8083:8083" # Not required if using the base install
    networks:
      - frontend