version: "3.8"

# Define networks
networks:
# This network gets created by my base-install compose file. Remove it if you aren't using that.
  frontend:
    external: true

# Create volumes
volumes:
  homebox_data:
    name: homebox_data

# Create homebox container
services:
  homebox:
    container_name: homebox
    image: ghcr.io/hay-kot/homebox:latest
    restart: unless-stopped
    volumes:
      - homebox_data:/data/
    networks:
      - frontend
    # ports:
      # - 3100:7745 # Not required if using the base install
    environment:
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=10
      - TZ=America/Toronto