# Define networks
networks:
# These networks get created by my base-install compose file. Remove them if you aren't using that.
  frontend:
    external: true
  backend:
    external: true

# Create volumes
volumes:
  nextcloud:
    name: nextcloud
  nextcloud_config:
    name: nextcloud_config
  nextcloud_data:
    name: nextcloud_data
  nextcloud_db:
    name: nextcloud_db
  nextcloud_db_data:
    name: nextcloud_db_data
  nextcloud_apps:
    name: nextcloud_apps

# Create nextcloud and nextcloud_db container
services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
      - nextcloud_config:/var/www/html/config
      - nextcloud_data:/var/www/html/data
      - nextcloud_apps:/var/www/html/custom_apps
    networks:
      - frontend
      - backend
    # ports:
      # - 443:443 # Not required if using the base install
    environment:
      - NEXTCLOUD_ADMIN_USER=username # This your admin username
      - NEXTCLOUD_ADMIN_PASSWORD=changeme # This your admin password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=changeme
      - MYSQL_HOST=nextcloud_db:3306
      - TRUSTED_PROXIES=nginx_proxy_manager
      - OVERWRITECLIURL=https://your.domain.here # Subsitute your domain
      - OVERWRITEHOST=your.domain.here # Substitute your domain
      - OVERWRITEPROTOCOL=https
      - TZ=America/Toronto

  nextcloud_db:
    container_name: nextcloud_db
    image: lscr.io/linuxserver/mariadb:latest
    restart: unless-stopped
    volumes:
      - nextcloud_db:/var/lib/mysql
      - nextcloud_db_data:/config
    networks:
      - backend
    # ports
      # - 3306:3306 # Not required if using the base install
    environment:
      - MYSQL_ROOT_PASSWORD=pleasechangeme
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - TZ=America/Toronto