version: "3.8"

# Define networks
networks:
# These networks get created by my base-install compose file. Remove them if you aren't using that.
  frontend:
    external: true
  backend:
    external: true

# Create volumes
volumes:
  wordpress_data:
    name: wordpress_data
  wordpress_db:
    name: wordpress_db

# Create wordpress, wordpress_db, and phpmyadmin containers
services:
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - frontend
      - backend
    # ports:
      # - "80:80" # Not required if using the base install
    environment:
      - WORDPRESS_DB_HOST=wordpress_db
      - WORDPRESS_DB_USER=my_wp_user
      - WORDPRESS_DB_PASSWORD=my_wp_user_password
      - WORDPRESS_DB_NAME=my_wp_database
      - TZ=America/Toronto
    depends_on:
      - wordpress_db
  
  wordpress_db:
    container_name: wordpress_db
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - backend
    # ports
      # - 3306:3306 # Not required if using the base install
    environment:
      - MYSQL_ROOT_PASSWORD=my_password_1234789
      - MYSQL_DATABASE=my_wp_database
      - MYSQL_USER=my_wp_user
      - MYSQL_PASSWORD=my_wp_user_password
      - TZ=America/Toronto
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: unless-stopped
    networks:
      - frontend
      - backend
    # ports:
      # - "80:80" # Not required if using the base install
    environment:
      - PMA_HOST=wordpress_db
      - MYSQL_ROOT_PASSWORD=my_password_1234789
    depends_on:
      - wordpress_db