version: "3.8"

# Define networks
networks:
# These networks get created by my base-install compose file. Remove them if you aren't using that.
  frontend:
    external: true
  backend:
    external: true

# Create volumes
volumes:
  ghost_data:
    name: ghost_data
  ghost_db:
    name: ghost_db

# Create ghost containers
services:
  ghost:
    container_name: ghost
    image: ghost:5-alpine
    restart: unless-stopped
    volumes:
      - ghost_data:/var/lib/ghost/content
    networks:
      - frontend
      - backend
    # ports:
      # - 8080:2368 # Not required if using the base install
    environment:
      - TZ=America/Toronto
      - database__client=mysql
      - database__connection__host=ghost_db
      - database__connection__user=root
      - database__connection__password=example
      - database__connection__database=ghost
      - url=https://your.blog.com
  
  ghost_db:
    container_name: ghost_db
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - ghost_db:/var/lib/mysql
    networks:
      - backend
    # ports:
      # - 3401:3401 # Not required if using the base install
    environment:
      - TZ=America/Toronto
      - MYSQL_ROOT_PASSWORD=example