# Define networks
networks:
# These networks get created by my base-install compose file. Remove them if you aren't using that.
  frontend:
    external: true

# Create volumes
volumes:
  memos_data:
    name: memos_data

# Create memos container
services:
  memos:
    container_name: memos
    image: neosmemo/memos:latest
    restart: unless-stopped
    volumes:
      - memos_data:/var/opt/memos
    networks:
      - frontend
    # ports:
      # - 5230:5230 # Not required if using the base install
    environment:
      - TZ=America/Toronto