version: "3.8"

# Define networks
networks:
# These networks get created by my base-install compose file. Remove them if you aren't using that.
  frontend:
    external: true

# Create volumes
volumes:
  config:
    name: config
  content:
    name: content
  plugins:
    name: plugins
  themes:
    name: themes

# Create example containers
services:
  pico-cms:
    container_name: pico-cms
    image: mhzawadi/picocms:latest
    restart: unless-stopped
    volumes:
      - config:/home/sites/picocms/config
      - content:/home/sites/picocms/content
      - plugins:/home/sites/picocms/plugins
      - themes:/home/sites/picocms/themes
    networks:
      - frontend
    # ports:
      # - 80:80 # Not required if using the base install
    environment:
      - TZ=America/Toronto