version: "3.8"

# Define networks
networks:
  frontend:
    external: true # This network exists because we created it with the base install
  backend:
    external: true # This network exists because we created it with the base install

# Define volumes
volumes:
  reactive_resume_db:
    name: reactive_resume_db
  reactive_resume_redis:
    name: reactive_resume_redis
  reactive_resume_minio:
    name: reactive_resume_minio

# Create containers
services:
  reactive_resume_client:
    image: amruthpillai/reactive-resume:latest
    restart: unless-stopped
    container_name: reactive_resume_client
    networks:
      - frontend
      - backend
    # ports:
      # - 3030:3000 # Not required if using the base install
    depends_on:
      - reactive_resume_db
      - reactive_resume_minio
      - reactive_resume_chrome
      - reactive_resume_redis
    environment:
      - PUBLIC_URL=http://resume.yoursite.com # Change this to your subdomain/domain
      - PUBLIC_SERVER_URL=http://resume.yoursite.com/api # Change this to your subdomain/domain **LEAVE "/api"**
  reactive_resume_db:
    image: postgres:15-alpine
    user: 1000:1000
    restart: unless-stopped
    container_name: reactive_resume_db
    networks:
      - backend
    volumes:
      - reactive_resume_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=changeme1
      - POSTGRES_PASSWORD=changeme2
      - POSTGRES_DB=changeme3
  reactive_resume_minio:
    image: minio/minio:latest
    restart: unless-stopped
    container_name: reactive_resume_minio
    networks:
      - backend
    volumes:
      - reactive_resume_minio:/data
    # ports:
      # - 9000:9000 # Not required if using the base install
    environment:
      MINIO_ROOT_USER: changeme4
      MINIO_ROOT_PASSWORD: changeme5
  reactive_resume_redis:
    image: redis:latest
    restart: unless-stopped
    container_name: reactive_resume_redis
    networks:
      - backend
    volumes:
      - reactive_resume_redis:/data
  reactive_resume_chrome:
    image: browserless/chrome:latest
    restart: unless-stopped
    container_name: reactive_resume_chrome
    networks:
      - backend
    env_file:
      - env.v4

