version: "3.8"

# Define networks
networks:
  frontend:
    external: true # This network exists because we created it with the base install

# Define volumes
volumes:
  freshrss_config:
    name: freshrss_config

# Create libreddit container
services:
  freshrss:
    container_name: freshrss
    image: lscr.io/linuxserver/freshrss:latest
    restart: always
    # ports:
      # - "8080:8080" # Not required if using the base install
    volumes:
      - freshrss_config:/config
    networks:
      - frontend